### ISSUE TITLE
Make the theme installable through tpm

### ISSUE THREAD

**Issue by PezCoder** [egel/tmux-gruvbox#1]
#### Thank you
❤️ First off, I absolutely loved this theme, the colours fits really well with my `gruvbox` theme.

#### What is this issue about ?
The current installation of tmux-gruvebox is simple but it requires cloning the repo & either moving the content to tmux config file or source the theme file from tmux (which I find better).

The process could be improved by creating this theme as a plugin of [TPM](https://github.com/tmux-plugins/tpm), which is a popular package manager for tmux.

Personally, since I've automated scripts, to setup the same environment across platforms or a new machine I prefer these package managers as they handle the cloning & everything for me.

I would be happy to work on it if you agree. Let me know your thoughts.

#### References
- [Creating a plugin tpm guide](https://github.com/tmux-plugins/tpm/blob/master/docs/how_to_create_plugin.md)
- [tmux-themepack plugin which is using it](https://github.com/jimeh/tmux-themepack)

**Comment by egel** [comment]
Hey @PezCoder, at first thank for this issue (nicely written with references). I'm ecstatic that you like the theme, along with other users 🙂

Regarding the idea of adding support for TPM themes, I would love to do it. Unfortunately, at the moment don't have much free time, but I already added this issue to my open-source TODO list. Hopefully, in near future, I should release a new version with the light version of the theme and with TPM support naturally.

BTW. If you would like to provide a PR, please feel free to do it 🙂 I'm always open to any opensource contribution activity 🙂

**Comment by PezCoder** [comment]
Thanks for the input, I'll start working on this today.. :)
