### ISSUE TITLE
How do I remove this?

### ISSUE THREAD

**Issue by kevindashgit** [egel/tmux-gruvbox#11]
I gave this plugin a shot and didn't like it, but now it seems I can't get rid of it? 
I still see the "theme" applied even though I don't have the plugin in my `.tmux.conf` and updated via `prefix + U`

Still see it :( :( :(

(btw the reason I didn't like it was because I lose functionality (* and - and Z indicators))

**Comment by anhari** [comment]
Should just need to delete it from ~/.tmux/plugins.

**Comment by kevindashgit** [comment]
@anhari I totally thought that's all it took too - but something is preserving things...
Here's `~/.tmux/plugins/`
![image](https://user-images.githubusercontent.com/9002097/58683001-afecb680-8327-11e9-9e1a-e35571ba928e.png)

But I still see this:
![image](https://user-images.githubusercontent.com/9002097/58683023-cdba1b80-8327-11e9-9201-673b550deedf.png)

**Comment by egel** [comment]
@kevindashgit, have you tried to uninstall the plugin via `prefix + alt + u` (not sure if only `prefix + u` is enough) from official TPM doc page https://github.com/tmux-plugins/tpm#uninstalling-plugins?

**Comment by kevindashgit** [comment]
@egel yup I can recall trying that too - good thought though.  I'm gonna go ahead and close this since I've moved on with my life and probably this is environmental. Thanks.
