### ISSUE TITLE
Arrows in the bar not displaying properly

### ISSUE THREAD

**Issue by BryanWesterveld** [egel/tmux-gruvbox#13]
Hey,

I noticed the arrow is not properly displayed. On the hollow side I noticed a tiny red line/border passing through it. Do you know what might have caused this? I have attached an image for clarity.

![tmux gruvbox theme](https://i.imgur.com/ZjA1A17.png)

**Comment by BryanWesterveld** [comment]
I think I"ll delete the arrows and roll with squares.

**Comment by willchao612** [comment]
This also occurs to me. How did you solve this issue? @DriftingBits

**Comment by willchao612** [comment]
Using a different terminal emulator like kitty might help.
