### ISSUE TITLE
Lower Left arrows are not displaying correctly 

### ISSUE THREAD

**Issue by Monksc** [egel/tmux-gruvbox#16]
My arrows on the bottom left look like this.
![Screen Shot 2021-02-19 at 10 06 03 AM](https://user-images.githubusercontent.com/9803478/108521871-2d91ec00-729a-11eb-8c97-bc70528697c9.png)

They used to look normal about 6 months ago. Like how they looked below
![Screen Shot 2021-02-19 at 10 05 23 AM](https://user-images.githubusercontent.com/9803478/108522068-6631c580-729a-11eb-94a9-0bc64652a882.png)

I use Alacrity and macOS Catalina if that helps. I feel like I may be missing something in my .tmux.conf or even Alacritty config. It also is not displaying correctly in the default terminal app on MacOS and never has.

**Comment by PezCoder** [comment]
For me, this happened with the recent upgrade from 0.4 to 0.7. I'm unsure of how these icons are rendered & who is the culprit here.

<img width="398" alt="Screenshot 2021-03-07 at 1 40 25 AM" src="https://user-images.githubusercontent.com/8057916/110219631-71196680-7ee6-11eb-87a6-628b36080932.png">

**Comment by PezCoder** [comment]
For now I changed the last three lines of `~/.tmux/plugins/tmux-gruvbox/tmux-gruvbox-dark.conf` to:

```
set-option -g status-right "#[fg=colour239, bg=colour237, nobold, nounderscore, noitalics]#[fg=colour246,bg=colour239] %Y-%m-%d | %H:%M #[fg=colour248, bg=colour239, nobold, noitalics, nounderscore]#[fg=colour237, bg=colour248] #h "

set-window-option -g window-status-current-format "#[fg=colour237, bg=colour214, nobold, noitalics, nounderscore]#[fg=colour239, bg=colour214] #I >#[fg=colour239, bg=colour214, bold] #W #[fg=colour214, bg=colour237, nobold, noitalics, nounderscore]"
set-window-option -g window-status-format "#[fg=colour237,bg=colour239,noitalics]#[fg=colour223,bg=colour239] #I >#[fg=colour223, bg=colour239] #W #[fg=colour239, bg=colour237, noitalics]"
```

Basically removes the `` character which alacrity is not able to render with `>` (for left status bar) or `|`  (for right one)

Seems to be an okayish workaround. The use to find the previous separator anyways weird.

Before:
<img width="1792" alt="Screenshot 2021-03-07 at 1 57 31 AM" src="https://user-images.githubusercontent.com/8057916/110219974-8c857100-7ee8-11eb-8369-84e486967c47.png">

After:
<img width="1790" alt="Screenshot 2021-03-07 at 1 57 44 AM" src="https://user-images.githubusercontent.com/8057916/110219977-91e2bb80-7ee8-11eb-910f-0ef6a29d392f.png">

**Comment by Monksc** [comment]
Turns out I just had to switch my font to Hack in my Alacrity settings.
