### ISSUE TITLE
Window zoomed indication missing

### ISSUE THREAD

**Issue by ijskegel** [egel/tmux-gruvbox#17]
When zooming the current window (using <prefix> z) there is no indication in the bar that the window is zoomed.

Possible solution could be to change `#W` to `#W#{?window_zoomed_flag,*Z,}` in the window-status-current-format setting. This adds a *Z indication when the window is zoomed.

**Comment by egel** [comment]
Hi @ijskegel! Great idea and thanks for sharing. I did not even know there is zoom mode 😉 it's really handy!

The implementation seems to be trivial, so I could propose something in the new PR.

**Comment by egel** [comment]
@ijskegel here https://github.com/egel/tmux-gruvbox/pull/19 is PR with the missing zoom feature you proposed. 

Would you take a look at it and let me know if this is what you looking for? Thanks in advance 😊

**Comment by ijskegel** [comment]
@egel, this is exactly what I was looking for. Thanks for fixing this!

**Comment by egel** [comment]
Great! Then I am merging this.
