### ISSUE TITLE
Transparent background on tmux 3.2

### ISSUE THREAD

**Issue by maharjanaman** [egel/tmux-gruvbox#18]
With tmux 3.2, background color is not showing all the way.
<img width="216" alt="Screen Shot 2021-04-16 at 10 10 48" src="https://user-images.githubusercontent.com/14164484/114971782-d0cb4000-9e9c-11eb-9f68-f320e6001f0f.png">

**Comment by marianaantunes** [comment]
Same problem here

<img width="229" alt="Screen Shot 2022-01-26 at 16 58 08" src="https://user-images.githubusercontent.com/46333060/151237490-81ec08df-24ca-40bc-b9e4-5342bbe58354.png">

**Comment by sarunmrzn** [comment]
any fix for this yet

**Comment by JulianVidal** [comment]
I am unsure how this could be implemented as an option for the theme but I got the transparency working.

![image](https://github.com/egel/tmux-gruvbox/assets/49546430/7e2e1705-cf4e-4646-8687-baffec797e85)

https://github.com/JulianVidal/dotfiles/blob/99b1b875ace6aec6b8193743db813153926db91e/tmux/tmux-gruvbox-dark.conf
