### ISSUE TITLE
feat: add date and time customization

### ISSUE THREAD

**Issue by samarulmeu** [egel/tmux-gruvbox#21]
Will it be possible (already exists?) a possibility to change date and time display? For example have something like `%d.%m.%Y`.

Thank you!

**Comment by egel** [comment]
Hi @samarulmeu, thanks so much for the issue.

TLDR; I can simply answer, yes! 🙂

I am currently working on enhancing the theme to provide more customization options to the theme. I imagine there will be an easy way to customize the desired slot with time to fit your needs.

If you are interested, you may take a look at #30 to see more.

Best

**Comment by samarulmeu** [comment]
Hi @egel!

Thank you for your help! Waiting for the setting to be available! 

Good work!

**Comment by egel** [comment]
Hey @samarulmeu, this feature should be already available for tests in [release/v2-0-0](https://github.com/egel/tmux-gruvbox/tree/release/v2-0-0) branch. Feel free to try it out 🙂

**Comment by samarulmeu** [comment]
Only now I've seen your comment. 

I'm using an automated plugin update, but for last days I get an error when trying to update

``` 
"tmux-gruvbox" update fail
    | fatal: couldn't find remote ref refs/heads/master
```

It seems you've renamed the branch. Should I do something?

**Comment by egel** [comment]
Hi @samarulmeu, and thanks for the feedback. Oh yes, some time ago I decided to migrate from `master` to `main` as the primary branch and did not update the master for a while then - therefore recently thought to clean it out. I am sorry for this inconvenience.

I think the simplest way would be to: 
- remove the plugin `rm -rf ~/.tmux/plugins/tmux-gruvbox`
- and reinstall it again via tpm [key-binding](https://github.com/tmux-plugins/tpm?tab=readme-ov-file#key-bindings) `<prefix> + I`. 

feel free to let me know if this worked for you.

Or if you plan to test the upcoming release branch with time adjustments - but then you may need to manually pull the repo and link it (see [dev section](https://github.com/egel/tmux-gruvbox?tab=readme-ov-file#development)).

**Comment by samarulmeu** [comment]
Thank you, @egel! Everything went smooth in upgrading. I am still waiting for the adjustments to hit the stable branch.

**Comment by egel** [comment]
Awesome, happy this worked for you @samarulmeu. 

And yeah, same! I also want to push this to main! As I am so excited to give those new great things to you all.

Although there are a couple of things that still need to be considered e.g.: btw that you remind me, what if someone is using old versions, or if someone's terminal does not support 16bit colors - so aka potential migration guide. 
generally, I do not expect huge changes (I tried to keep compatibility as much as possible), but there will be slight differences in themes, and people need to know them and feel comfortable :)

Also, feel free to leave feedback if you try out the release/v2.0.0. I am so much open to constructive critique and suggesting better solutions.

**Comment by samarulmeu** [comment]
I think that a migration guide is also necessary.

Keep up the good woork!

**Comment by samarulmeu** [comment]
I tried to test the 2.0.0 version but I can not set the date as I wanted. This is the setting i put in my `tmux.conf`

```
set -g @tmux-gruvbox-right-status-x '%d-%m-%Y'
```

Should I do something more or the setting is not right?

**Comment by egel** [comment]
Hmm... very interesting. what timezone, OS, and terminal emulator do you use?

generally whatever I tried so far with `%d-%m-%Y` gives me the same results format following `DD-MM-YYYY` both for macOS & linux Ubuntu (checked with alacritty & iTerm).

also tested successfully with different using `date` with different timezone & separators like e.g. `.` 

```bash
set -g @tmux-gruvbox-right-status-x '#(TZ="America/Chicago" date +%d.%m.%Y)'
```

if this is also not working, try with double `%%`, as this could be related to interpolation with displaying different timezones ([source](https://stackoverflow.com/a/39868365/1977012)). 

```bash
set -g @tmux-gruvbox-right-status-x '#(date +%%d.%%m.%%Y)'
```


> Of course, the timezone below is not required, just to demonstrate purpose.
> 
> ```
> set -g @tmux-gruvbox-right-status-x '#(TZ="America/Chicago" date +%%d.%%m.%%Y)'
> ```

**Comment by samarulmeu** [comment]
Hi @egel!

I am using xterm in Devuan Linux. 

In the end it seems to work, but now I get some differences in the color palette. 

This is the old status bar

![old](https://github.com/user-attachments/assets/4dd4a736-f9c5-4929-8631-c3249da240b3)

and this one is with v2

![new](https://github.com/user-attachments/assets/c5d87af0-03a9-4aa2-b242-2a21add88be8)

Did something change or it is still something on my part?

**Comment by egel** [comment]
yes, therefore I saw the inevitable need & explanation in the migration guide before the official release. ;)

in v2 will support a 16-bit color palette to get a richer color experience, therefore the `light` theme will use 16-bit colors.
if you are interested in using only 256 color palettes feel free to set the theme to `light256`.

**Comment by samarulmeu** [comment]
Thank you for your explanation. All of this should be added to the migration guide. 

Let's see how it goes! I will be back with feedback after the release.

**Comment by egel** [comment]
done, closing after merging release/v2.0.0

**Comment by samarulmeu** [comment]
@egel Hello! 

I am trying to display the date in local format but with no success. 

Here is my code

`#set -g @tmux-gruvbox-right-status-x '#(LC_TIME="ro_RO.UTF-8" date +"%A, %e %B %Y")'`

I tried even this:

`set -g @tmux-gruvbox-right-status-x '#(export LC_ALL="ro_RO.UTF-8" date +"%A, %e %B %Y")'`

Thank you!

**Comment by egel** [comment]
Hi @samarulmeu! 

Sorry to hear that it doesn't work out of the box. I had some problems with simulating your Devuan Linux (xterm) config on my silicon mac - it just doesn't work... 
Currently, I am lacking a free/unused amd64 CPU, in order to simulate it.

Have you maybe tried with double `%` as I mentioned in README section for date? Someone already mentioned this to me once, some systems require this trick, therefore I put this info there. 
Try maybe with something like the below - although must mention I have no idea without a test environment if this would even work:

```bash
set -g @tmux-gruvbox-right-status-x '#(date +"%%A, %%e %%B %%Y")'
```

**Comment by samarulmeu** [comment]
Hi @egel!

Thank you for your answer. Indeed using the double `%` worked and now I have localized date. Maybe you should add this in the configuration information. 

All the best!

**Comment by egel** [comment]
Great @samarulmeu! I am happy that this worked for you - hope you enjoy it.
I also quickly checked, and the info about this is already in [README](https://github.com/egel/tmux-gruvbox/commit/80ca5fda100f295251ca0d06ff2a9314abab235f) at least with the latest change since Nov '24.
