### ISSUE TITLE
Gruvbox light theme version

### ISSUE THREAD

**Issue by egel** [egel/tmux-gruvbox#3]
### Description
As a developer,

I want to use a light theme Gruvbox for Tmux

so that it can better fit my light terminal theme.

### Acceptance

- [x] implement light Gruvbox theme
- [x] adjust color to nicely fit the light Gruvbox theme for vim and terminal itself

### Additional Information

*   Depends on issue(s): -
*   Related to issue(s): -

**Comment by maharjanaman** [comment]
Any update on this?

**Comment by egel** [comment]
Hi @maharjanaman. Thanks for the message and sharing the interest in this new feature. 
Currently I’m on holidays up to 15.01.2020 🌴. When I’ll come back, I’ll try to push this topic forward 🙂

If you have some propositions how to map Gruvbox colors into the 256 color palette, I would love to hear it because in Dec, after several tries, I was still not satisfied with the results for white theme.

**Comment by egel** [comment]
Hey @maharjanaman, I'm back with some good news. I've tried to give another round and tackle down this gruvbox white theme using only 256 color palette. The picture below, for now, is the only mockup. I wanted to play with it a bit, so all the things could nicely fit together. My goal was to fit it with Vim's light gruvbox theme and still, eyes would not be hurt much ;)
What do you think about it? I'm open to any suggestion/proposition before I will continue with it.

![gruvbox_light_theme_256color_v1](https://user-images.githubusercontent.com/3322106/74396037-2d524b80-4e11-11ea-8081-90484cc0db0c.png)

**Comment by egel** [comment]
Great @maharjanaman, then I will start implementing as it is :)

**Comment by egel** [comment]
Hey, today I've pushed a working draft of light theme in-branch #5. Let me know @maharjanaman if this is working for you.

Some colors might be still a bit laggy, but no spoilers until you'll try it 😁

Any feedback is a warm welcome in #5

**Comment by egel** [comment]
The final version looks at my local macOS terminal like this.

![Screenshot 2020-10-29 at 18 58 40](https://user-images.githubusercontent.com/3322106/97632602-09807580-1a33-11eb-96bf-002141875a9d.png)
