### ISSUE TITLE
Theme broken recently, will not load

### ISSUE THREAD

**Issue by onlyhavecans** [egel/tmux-gruvbox#37]
Since https://github.com/egel/tmux-gruvbox/commit/bf07efd3227d01d5b2a97cf04ccd4f5f69a0ddd7 the theme no longer loads on my system and leaves me with the default status bar

OS: Linux Mint wilma 22 x86_64
Shell: fish 3.7.1 / GNU bash, version 5.2.32(1)-release
Terminal: tmux 3.4

Loaded with
```
# Theme
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'light'
```

I tried re-sourcing config, killing the server, and restarting it, but I can't get the theme to load.
If I revert to e2a29912 it works again.

If there is more information I can provide please let me know. I really like this theme.

**Comment by DaveWillkomm** [comment]
I was able to fix this on my machine with #38. Hope this helps others.

**Comment by egel** [comment]
Thanks @onlyhavecans & @DaveWillkomm for the report & efforts. The problem should be resolved in the main branch. 

Feel free to check it out, and report in case of problems - e.g.:

- remove dir with the theme `~/.tmux/plugins/tmux-gruvbox`
- reinstall plugins via tmux `<prefix>` + `I`
- alternatively open new window with new tmux session

**Comment by onlyhavecans** [comment]
Thanks for addressing this!

**Comment by egel** [comment]
You are very welcome! 

I want that people enjoy the theme. I hope everything went back to norm for you.
